[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "18"

[build]
  publish = "docs/.vuepress/dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store && sed -i \"s/\/vuepress-blog\//\//g\" docs/.vuepress/components/constants/constants.ts && cd ./docs/.vuepress/realcugan-ncnn-webassembly && bash build.sh && npx pnpm docs:build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
