name: Deploy docs

on:
  push:
    branches:
      - master

jobs:
  deploy-docs:
    strategy:
      matrix:
        node-version: [18]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2147483647

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Install submodules
        run: git submodule update --init

      - name: Build wasm files
        run: cd ./docs/.vuepress/realcugan-ncnn-webassembly && bash build.sh

      - name: Build Docs
        run: |-
          pnpm docs:build
          > docs/.vuepress/dist/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.6.8
        with:
          branch: gh-pages
          folder: docs/.vuepress/dist
